packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core dependencies
  typescript: ^5.8.3
  "@types/node": ^22
  zod: ^3.24.4

  # React/Next.js
  react: ^19.2.0
  react-dom: ^19.2.0
  next: ^16.0.4

  # Tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  turbo: ^2.6.1

  # ESLint plugins
  "@typescript-eslint/eslint-plugin": ^8.27.0
  "@typescript-eslint/parser": ^8.27.0
  "@eslint/eslintrc": ^3.3.1
  eslint-config-next: ^16.0.4
  eslint-config-prettier: ^10.1.1
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-react-hooks: ^5.2.0

  # XMCP
  xmcp: ^0.4.0
